# Generated by Django 3.2 on 2021-04-23 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210423_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provier',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='groupNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='max_distance_preference',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='patient',
            name='ssn',
            field=models.CharField(default=django.utils.timezone.now, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='address_line2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
