# Generated by Django 3.1.2 on 2021-04-24 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staticInfo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("appointment_time", models.DateTimeField()),
                ("available_number", models.IntegerField()),
                ("status", models.CharField(max_length=255)),
                ("expire_time", models.DateTimeField()),
                (
                    "slot_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staticInfo.weeklytimeslot",
                    ),
                ),
            ],
        ),
    ]
