# Generated by Django 3.1.2 on 2021-04-23 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staticInfo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("appointment_time", models.DateTimeField()),
                ("available_number", models.IntegerField()),
                ("status", models.CharField(max_length=255)),
                ("expire_time", models.DateTimeField()),
                (
                    "patient_username",
                    models.ManyToManyField(
                        related_name="patient_username", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "provider_username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slot_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staticInfo.weeklytimeslot",
                    ),
                ),
            ],
        ),
    ]
