# Generated by Django 3.1.2 on 2021-05-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210428_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='remaining_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
