# Generated by Django 3.2 on 2021-05-05 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_rename_appointment_id_offerappointment_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerappointment',
            name='expire_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
