# Generated by Django 3.1.2 on 2021-04-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="max_distance_preferences",
            field=models.FloatField(default=0, null=True),
        ),
    ]
