# Generated by Django 3.1.2 on 2021-05-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address_line2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
