# Generated by Django 3.2 on 2021-04-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_patient_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address_line2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='max_distance_preferences',
            field=models.FloatField(default=500),
        ),
    ]
