# Generated by Django 3.1.2 on 2021-04-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210425_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address_line2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
