# Generated by Django 3.1.2 on 2021-05-01 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staticInfo', '0002_weeklytimeslot_patient'),
        ('user', '0004_auto_20210430_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='group_number',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='staticInfo.prioritygroup'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='max_distance_preferences',
            field=models.FloatField(default=50, null=True),
        ),
    ]
