# Generated by Django 3.2 on 2021-04-30 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staticInfo', '0002_weeklytimeslot_patient'),
        ('user', '0006_alter_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='group_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staticInfo.prioritygroup'),
        ),
    ]
