# Generated by Django 3.1.2 on 2021-04-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("staticInfo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklytimeslot",
            name="patient",
            field=models.ManyToManyField(to="user.Patient"),
        ),
    ]
